LOAD DATA
INFILE 'PRACOWNICY.csv'
BADFILE 'PRACOWNICY.bad'
DISCARDFILE 'PRACOWNICY.dsc'
REPLACE INTO TABLE PRACOWNICY
FIELDS TERMINATED BY ","
TRAILING NULLCOLS
(pracownik_id,staz,osoba_id,salon_id,specjalizacja_id)