LOAD DATA
INFILE 'PRZEDSTAWICIEL.csv'
BADFILE 'PRZEDSTAWICIEL.bad'
DISCARDFILE 'PRZEDSTAWICIEL.dsc'
REPLACE INTO TABLE PRZEDSTAWICIEL
FIELDS TERMINATED BY ","
TRAILING NULLCOLS
(przedstawiciel_id,osoba_id,siec_id)