LOAD DATA
INFILE 'REGION_SALONU.csv'
BADFILE 'REGION_SALONU.bad'
DISCARDFILE 'REGION_SALONU.dsc'
REPLACE INTO TABLE REGION_SALONU
FIELDS TERMINATED BY ","
TRAILING NULLCOLS
(region_salonu_id,nazwa_regionu)