LOAD DATA
INFILE 'SPECJALIZACJA.csv'
BADFILE 'SPECJALIZACJA.bad'
DISCARDFILE 'SPECJALIZACJA.dsc'
REPLACE INTO TABLE SPECJALIZACJA
FIELDS TERMINATED BY ","
TRAILING NULLCOLS
(specjalizacja_id,nazwa_specjalizacji,dodatkowe_informacje)