LOAD DATA
INFILE 'TYP_PLATNOSCI.csv'
BADFILE 'TYP_PLATNOSCI.bad'
DISCARDFILE 'TYP_PLATNOSCI.dsc'
REPLACE INTO TABLE TYP_PLATNOSCI
FIELDS TERMINATED BY ","
TRAILING NULLCOLS
(typ_platnosci_id,forma_platnosci)