LOAD DATA
INFILE 'WLASCICIEL_SALONU.csv'
BADFILE 'WLASCICIEL_SALONU.bad'
DISCARDFILE 'WLASCICIEL_SALONU.dsc'
REPLACE INTO TABLE WLASCICIEL_SALONU
FIELDS TERMINATED BY ","
TRAILING NULLCOLS
(wlasciciel_id,osoba_id,salon_id)